name: My workflow ## nameof the workflow
on: workflow_dispatch ##  event which triggers the workflows

jobs:
  my-job-one:
    runs-on: ubuntu-latest
    steps:
      - run: echo "first step"
  my-second-job:
    runs-on: ubuntu-latest
    needs:  my-job-one
    steps:
      - uses: actions/setup-python@v6
        name: python version
        with:
           python-version: '3.13' 
      - name: python version check 
        run: python --version
