name: My workflow ## nameof the workflow
on: workflow_dispatch ##  event which triggers the workflows

jobs:
  my-job-one:
    runs-on: ubuntu-latest
    steps:
      - run: echo "first step"
  my-second-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "second step"
